version: "3"

services:
  workload_frontend_production:
    container_name: workload_frontend_production
    build:
      context: .
      dockerfile: production.dockerfile
    restart: unless-stopped
    volumes:
      - ./build:/usr/web/build
      - ./.env:/usr/web/.env
      - ./app.js:/usr/web/app.js
      - ./logs:/usr/web/logs
    command: "node app.js"
    ports:
      - 3001:3000
    env_file:
      - .env
    networks:
      - default
      - webproxy
    environment:
      VIRTUAL_HOST: workload.sc.su.ac.th

networks:
    default:
      name: workload
      external: true
    webproxy:
      name: webproxy
      external: true
  
